# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('catalog', '0005_auto_20170323_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'movie categories',
            },
        ),
        migrations.AddField(
            model_name='moviepage',
            name='genres',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='catalog.MovieGenre'),
        ),
    ]
