# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('catalog', '0006_auto_20170323_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'verbose_name_plural': 'movie genres'},
        ),
    ]
